[2024-02-23 15:05:06,623 submission_checker.py:3385 ERROR] closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99.9/Offline is missing code_dir closed/HPE/code/XSym
0004
f223f728fa0e3cd933d47c1feca68f5b
gptj/
[2024-02-23 15:05:06,623 submission_checker.py:2932 ERROR] closed/HPE/measurements/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99.9/Offline measurement_dir has issues
[2024-02-23 15:05:06,623 submission_checker.py:3170 ERROR] closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99.9 does not have all required scenarios, missing {'Offline', 'Server'}
[2024-02-23 15:05:06,623 submission_checker.py:3385 ERROR] closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99/Offline is missing code_dir closed/HPE/code/XSym
0004
f223f728fa0e3cd933d47c1feca68f5b
gptj/
[2024-02-23 15:05:06,623 submission_checker.py:2932 ERROR] closed/HPE/measurements/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99/Offline measurement_dir has issues
[2024-02-23 15:05:06,623 submission_checker.py:3170 ERROR] closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99 does not have all required scenarios, missing {'Offline', 'Server'}
[2024-02-23 15:05:06,623 submission_checker.py:3662 INFO] ---
[2024-02-23 15:05:06,623 submission_checker.py:3668 INFO] ---
[2024-02-23 15:05:06,623 submission_checker.py:3671 ERROR] NoResults closed/HPE/measurements/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99.9/Offline
[2024-02-23 15:05:06,623 submission_checker.py:3671 ERROR] NoResults closed/HPE/measurements/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99/Offline
[2024-02-23 15:05:06,623 submission_checker.py:3671 ERROR] NoResults closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99
[2024-02-23 15:05:06,623 submission_checker.py:3671 ERROR] NoResults closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99.9
[2024-02-23 15:05:06,623 submission_checker.py:3671 ERROR] NoResults closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99.9/Offline
[2024-02-23 15:05:06,623 submission_checker.py:3671 ERROR] NoResults closed/HPE/results/HPE_ProLiant_DL380a_L40S_PCIe_48GBx4_TRT/gptj-99/Offline
[2024-02-23 15:05:06,623 submission_checker.py:3753 INFO] ---
[2024-02-23 15:05:06,623 submission_checker.py:3754 INFO] Results=0, NoResults=6, Power Results=0
[2024-02-23 15:05:06,623 submission_checker.py:3761 INFO] ---
[2024-02-23 15:05:06,623 submission_checker.py:3762 INFO] Closed Results=0, Closed Power Results=0

[2024-02-23 15:05:06,623 submission_checker.py:3767 INFO] Open Results=0, Open Power Results=0

[2024-02-23 15:05:06,623 submission_checker.py:3772 INFO] Network Results=0, Network Power Results=0

[2024-02-23 15:05:06,623 submission_checker.py:3777 INFO] ---
[2024-02-23 15:05:06,623 submission_checker.py:3779 INFO] Systems=0, Power Systems=0
[2024-02-23 15:05:06,623 submission_checker.py:3780 INFO] Closed Systems=0, Closed Power Systems=0
[2024-02-23 15:05:06,623 submission_checker.py:3785 INFO] Open Systems=0, Open Power Systems=0
[2024-02-23 15:05:06,623 submission_checker.py:3790 INFO] Network Systems=0, Network Power Systems=0
[2024-02-23 15:05:06,623 submission_checker.py:3795 INFO] ---
[2024-02-23 15:05:06,623 submission_checker.py:3797 ERROR] SUMMARY: submission has errors
